### Create Debt
POST http://localhost:8080/debts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsInVzZXJJZCI6IjY1Y2FkNjlmZTliZTYzMTE0YzE4MDk3OCIsImlhdCI6MTcwNzc5NTQxNCwiZXhwIjoxNzA3ODgxODE0fQ.MwtKtuinBrS34WkfPHdepR9qgRFo44nFHb4jpD6dK4s

{
  "name": "Debt 1",
  "amount": 1000,
  "interestRate": 0.1,
  "dueDate": "2024-03-05T00:00:00.000Z",
  "minimumPayment": 100,
  "paymentDate": "2024-03-05T00:00:00.000Z",
  "remainingBalance": 1000,
  "paymentsRemaining": 10,
  "initialPaymentTerm": 10
}


# export class CreateDebtDto {
#   @IsNotEmpty()
#   @IsString()
#   readonly name: string;

#   @IsNotEmpty()
#   @IsNumber()
#   readonly amount: number;

#   @IsOptional()
#   @IsNumber()
#   readonly interestRate?: number;

#   @IsOptional()
#   @IsDate()
#   readonly dueDate?: Date;

#   @IsOptional()
#   @IsNumber()
#   readonly minimumPayment?: number;

#   @IsOptional()
#   @IsDate()
#   readonly paymentDate?: Date;

#   @IsOptional()
#   @IsNumber()
#   readonly remainingBalance?: number;

#   @IsOptional()
#   @IsNumber()
#   readonly paymentsRemaining?: number;

#   @IsOptional()
#   @IsNumber()
#   readonly initialPaymentTerm?: number;

#   // ... add other fields as needed
# }
